-- H2 本地文件数据库初始化脚本。
-- 深海网箱养殖：鱼苗批次、投饵计划、水下传感器、传感器读数、投饵记录、存活率报告、出网批次。

CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

-- 鱼苗批次（投放入网箱的一批鱼苗）
CREATE TABLE IF NOT EXISTS t_fish_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no VARCHAR(32) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    species VARCHAR(64) NOT NULL,
    fingerling_count INTEGER NOT NULL,
    average_weight_g DECIMAL(10,2),
    status VARCHAR(16) NOT NULL DEFAULT 'BREEDING',
    stocking_time TIMESTAMP NOT NULL,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_fish_batch_no UNIQUE (batch_no)
);
CREATE INDEX IF NOT EXISTS idx_fish_batch_cage ON t_fish_batch (cage_no);
CREATE INDEX IF NOT EXISTS idx_fish_batch_status ON t_fish_batch (status);

-- 投饵计划
CREATE TABLE IF NOT EXISTS t_feeding_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    feed_type VARCHAR(64) NOT NULL,
    daily_amount_kg DECIMAL(10,2) NOT NULL,
    feed_frequency INTEGER NOT NULL DEFAULT 1,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_feeding_plan_no UNIQUE (plan_no)
);
CREATE INDEX IF NOT EXISTS idx_feeding_plan_batch ON t_feeding_plan (batch_id);

-- 水下传感器
CREATE TABLE IF NOT EXISTS t_underwater_sensor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_no VARCHAR(32) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    sensor_type VARCHAR(32) NOT NULL,
    metric_unit VARCHAR(16) NOT NULL,
    depth_m DECIMAL(6,2),
    install_time TIMESTAMP NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ONLINE',
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sensor_no UNIQUE (sensor_no)
);
CREATE INDEX IF NOT EXISTS idx_sensor_cage ON t_underwater_sensor (cage_no);

-- 水下传感器读数
CREATE TABLE IF NOT EXISTS t_sensor_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_no VARCHAR(32) NOT NULL,
    sensor_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    metric_value DECIMAL(12,4) NOT NULL,
    reading_time TIMESTAMP NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sensor_reading_no UNIQUE (reading_no)
);
CREATE INDEX IF NOT EXISTS idx_reading_sensor_time ON t_sensor_reading (sensor_id, reading_time);
CREATE INDEX IF NOT EXISTS idx_reading_cage_time ON t_sensor_reading (cage_no, reading_time);

-- 投饵记录（实际投饵量；posted 表示已落账，落账后不可删除/不可改金额）
CREATE TABLE IF NOT EXISTS t_feeding_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    plan_id BIGINT,
    cage_no VARCHAR(32) NOT NULL,
    feed_type VARCHAR(64) NOT NULL,
    amount_kg DECIMAL(10,2) NOT NULL,
    feeding_time TIMESTAMP NOT NULL,
    posted SMALLINT NOT NULL DEFAULT 0,
    posted_time TIMESTAMP,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_feeding_record_no UNIQUE (record_no)
);
CREATE INDEX IF NOT EXISTS idx_feeding_record_batch ON t_feeding_record (batch_id);

-- 存活率报告
CREATE TABLE IF NOT EXISTS t_survival_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    alive_count INTEGER NOT NULL,
    survival_rate DECIMAL(7,4) NOT NULL,
    report_time TIMESTAMP NOT NULL,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_survival_report_no UNIQUE (report_no)
);
CREATE INDEX IF NOT EXISTS idx_survival_report_batch ON t_survival_report (batch_id);

-- 出网批次（accepted 表示已验收，验收后不可删除）
CREATE TABLE IF NOT EXISTS t_harvest_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_no VARCHAR(32) NOT NULL,
    fish_batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    harvest_count INTEGER NOT NULL,
    total_weight_kg DECIMAL(12,2) NOT NULL,
    harvest_time TIMESTAMP NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    accepted_time TIMESTAMP,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_harvest_no UNIQUE (harvest_no)
);
CREATE INDEX IF NOT EXISTS idx_harvest_fish_batch ON t_harvest_batch (fish_batch_id);

-- 定时/手工批量任务互斥锁：同一任务全局一行；owner_token 标识持锁执行方，
-- lease_expire_time 为租约到期时间：执行方异常退出（JVM 崩溃/kill -9）后租约到期，
-- 下一次触发可接管，不会永久阻塞。
CREATE TABLE IF NOT EXISTS t_task_lock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lock_name VARCHAR(64) NOT NULL,
    owner_token VARCHAR(64) NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    lease_expire_time TIMESTAMP NOT NULL,
    CONSTRAINT uk_task_lock_name UNIQUE (lock_name)
);

-- 任务执行台账：同一任务同一业务周期唯一一行。
-- RUNNING 执行中 / SUCCESS 成功（终态，重复触发短路）/ FAILED 失败（可重试）。
-- 成功终态 + (task_name, period) 唯一约束保证一个业务周期最多处理一次。
CREATE TABLE IF NOT EXISTS t_task_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR(64) NOT NULL,
    period VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    trigger_source VARCHAR(16),
    attempts INTEGER NOT NULL DEFAULT 1,
    posted_count INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(500),
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_task_run_period UNIQUE (task_name, period)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('aquaculture-2', '投饵监测批量落账定时任务：租约任务锁与业务周期幂等台账');

-- 网箱观测数据（CSV 批量导入落地区）。
-- 幂等业务键 = 航次号 + 网箱号 + 采样时刻（航次断网重复上传同一文件时，行级 upsert 保证不重复入账）。
-- 联动生成的投饵记录/存活率报告/传感器读数主键回写在本行上，用于“已落账/已验收不得覆盖”判定。
CREATE TABLE IF NOT EXISTS t_cage_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_no VARCHAR(32) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    observed_at TIMESTAMP NOT NULL,
    feed_amount_kg DECIMAL(10,2),
    survival_rate DECIMAL(7,4),
    sensor_value DECIMAL(12,4),
    sensor_unit VARCHAR(16),
    source_device VARCHAR(32),
    feeding_record_id BIGINT,
    survival_report_id BIGINT,
    sensor_reading_id BIGINT,
    import_id BIGINT NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cage_obs_key UNIQUE (voyage_no, cage_no, observed_at)
);
CREATE INDEX IF NOT EXISTS idx_cage_obs_cage ON t_cage_observation (cage_no, observed_at);
CREATE INDEX IF NOT EXISTS idx_cage_obs_voyage ON t_cage_observation (voyage_no);

-- 观测数据 CSV 导入批次台账：file_checksum（SHA-256）唯一。
-- 航次断网恢复后重复上传同一文件 → 校验和命中 → 直接返回首次处理结果（文件级幂等）；
-- 存在失败/未完成分片时续传这些分片（分片级重试）。
CREATE TABLE IF NOT EXISTS t_obs_import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_no VARCHAR(40) NOT NULL,
    file_name VARCHAR(255),
    file_checksum VARCHAR(64) NOT NULL,
    file_path VARCHAR(512),
    total_rows INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL,
    error_message VARCHAR(500),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_obs_import_no UNIQUE (import_no),
    CONSTRAINT uk_obs_import_checksum UNIQUE (file_checksum)
);

-- 导入分片台账：大文件按 shard-size 切分，逐片独立处理。
-- PENDING 待处理 / RUNNING 处理中（僵死可接管）/ SUCCESS 全部成功 / PARTIAL 完成但有失败行 / FAILED 分片级异常（可重试）。
CREATE TABLE IF NOT EXISTS t_obs_import_shard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL,
    shard_index INTEGER NOT NULL,
    start_idx INTEGER NOT NULL,
    end_idx INTEGER NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    row_count INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(500),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_obs_import_shard UNIQUE (import_id, shard_index)
);
CREATE INDEX IF NOT EXISTS idx_obs_shard_import ON t_obs_import_shard (import_id);

-- 逐行处理明细：每行一条（SUCCESS/UPDATED/SKIPPED/FAILED）。
-- 失败行保留原始行号、字段名、原始值与失败原因，供定位修复后重新上传。
CREATE TABLE IF NOT EXISTS t_obs_import_row (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL,
    shard_id BIGINT,
    line_no INTEGER NOT NULL,
    business_key VARCHAR(128),
    outcome VARCHAR(16) NOT NULL,
    field_name VARCHAR(32),
    raw_value VARCHAR(255),
    raw_line VARCHAR(1000),
    error_reason VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_obs_row_import ON t_obs_import_row (import_id, outcome);
CREATE INDEX IF NOT EXISTS idx_obs_row_shard ON t_obs_import_row (shard_id);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('obs-import-3', '观测数据CSV批量导入：校验和+业务键两级幂等、分片可重试、逐行隔离明细');

-- =====================================================================
-- 深海网箱养殖批次与投饵监测时序规则计算
-- =====================================================================

-- 网箱海区档案：对象（网箱）所属海区与业务时区，是“按对象时区归算”的时区来源。
-- 潮次登记/规则计算均以本表登记的时区为准；潮次落成时快照海区与时区，档案后续调整不影响历史潮次。
CREATE TABLE IF NOT EXISTS t_cage_sea_area (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cage_no VARCHAR(32) NOT NULL,
    sea_area VARCHAR(64) NOT NULL,
    time_zone VARCHAR(64) NOT NULL,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cage_sea_area_cage UNIQUE (cage_no)
);

-- 时序规则（版本化）：把一日 24h 划分为峰值/平段/谷值等业务区间，区间内投饵量按系数折算。
-- start_minute/end_minute 为日内分钟（0..1440），左闭右开 [start, end)；
-- end_minute <= start_minute 表示跨午夜区间（如 22:00-02:00）。
-- 同一 rule_code 的版本单调递增；启用后不能原地修改，调整须新建版本；
-- 启用新版本时同 code 旧版本自动退役；启用前校验与全部在启规则区间不重叠。
CREATE TABLE IF NOT EXISTS t_ts_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code VARCHAR(32) NOT NULL,
    version_no INT NOT NULL,
    rule_type VARCHAR(16) NOT NULL,
    start_minute INT NOT NULL,
    end_minute INT NOT NULL,
    coefficient DECIMAL(12,4) NOT NULL,
    status VARCHAR(16) NOT NULL,
    enabled_time TIMESTAMP,
    retired_time TIMESTAMP,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ts_rule_code_version UNIQUE (rule_code, version_no)
);
CREATE INDEX IF NOT EXISTS idx_ts_rule_status ON t_ts_rule (status);

-- 潮次：一次潮汐过程的开始/结束时刻（UTC 存储），左闭右开 [start_at_utc, end_at_utc)。
-- 跨午夜潮次按网箱所在海区时区归属业务日：business_date = start_at_utc 在海区时区下的当地日期。
-- sea_area/time_zone 为登记时刻的档案快照，档案调整后历史潮次归属不变。
CREATE TABLE IF NOT EXISTS t_tide_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tide_no VARCHAR(40) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    sea_area VARCHAR(64) NOT NULL,
    time_zone VARCHAR(64) NOT NULL,
    start_at_utc TIMESTAMP NOT NULL,
    end_at_utc TIMESTAMP NOT NULL,
    business_date DATE NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tide_no UNIQUE (tide_no)
);
CREATE INDEX IF NOT EXISTS idx_tide_cage_time ON t_tide_session (cage_no, start_at_utc, end_at_utc);
CREATE INDEX IF NOT EXISTS idx_tide_biz_date ON t_tide_session (cage_no, business_date);

-- 投饵监测观测：观测时刻统一按 UTC 存储，归算时换算到网箱海区时区。
CREATE TABLE IF NOT EXISTS t_feed_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obs_no VARCHAR(40) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    observed_at_utc TIMESTAMP NOT NULL,
    feed_amount_kg DECIMAL(10,3) NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_feed_obs_no UNIQUE (obs_no)
);
CREATE INDEX IF NOT EXISTS idx_feed_obs_batch_time ON t_feed_observation (batch_id, observed_at_utc);
CREATE INDEX IF NOT EXISTS idx_feed_obs_cage_time ON t_feed_observation (cage_no, observed_at_utc);

-- 时序规则计算结果：同一批次同一业务日唯一一行（并发重算不会产生两份结果）。
-- 重算采用 CALCULATING 状态 CAS 抢占，明细在同一事务内整体替换。
-- 各区间合计为 BigDecimal 精确累计后在最终步骤统一舍入（HALF_UP，2 位小数）。
-- rule_snapshot 为计算当时启用规则（含版本号）的 JSON 快照，历史结果读取当时快照。
CREATE TABLE IF NOT EXISTS t_ts_calc_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    business_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    obs_total INT NOT NULL DEFAULT 0,
    obs_matched INT NOT NULL DEFAULT 0,
    obs_unmatched INT NOT NULL DEFAULT 0,
    peak_total_kg DECIMAL(18,2),
    flat_total_kg DECIMAL(18,2),
    valley_total_kg DECIMAL(18,2),
    total_weighted_kg DECIMAL(18,2),
    rule_snapshot VARCHAR(4000),
    calc_time TIMESTAMP,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ts_calc_batch_date UNIQUE (batch_id, business_date)
);

-- 计算明细：每条命中观测一行，固化潮次快照与规则版本快照（规则切换不影响历史明细）。
-- weighted_kg 保留未舍入的精确乘积，舍入只在结果合计层统一执行。
CREATE TABLE IF NOT EXISTS t_ts_calc_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id BIGINT NOT NULL,
    obs_id BIGINT NOT NULL,
    obs_no VARCHAR(40) NOT NULL,
    observed_at_utc TIMESTAMP NOT NULL,
    obs_local_time VARCHAR(8) NOT NULL,
    tide_session_id BIGINT NOT NULL,
    tide_no VARCHAR(40) NOT NULL,
    tide_start_utc TIMESTAMP NOT NULL,
    tide_end_utc TIMESTAMP NOT NULL,
    rule_id BIGINT NOT NULL,
    rule_code VARCHAR(32) NOT NULL,
    rule_version INT NOT NULL,
    rule_type VARCHAR(16) NOT NULL,
    coefficient DECIMAL(12,4) NOT NULL,
    feed_amount_kg DECIMAL(10,3) NOT NULL,
    weighted_kg DECIMAL(18,8) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ts_calc_detail_result ON t_ts_calc_detail (result_id);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('ts-rule-calc-4', '时序规则计算：版本化峰平谷规则、潮次左闭右开跨日归属、快照留存与并发幂等重算');

-- =====================================================================
-- 网箱替换/转移（换箱/转场）：不可断裂的对象时间链
-- =====================================================================

-- 迁移链：同一鱼群（鱼苗批次）在其生命周期内每换一次箱/转一次场产生一个迁移事件，
-- 链上事件按 seq_no 单调递增、首尾网箱相接，形成不可断裂的时间链。
-- current_cage_no/current_seq 为链头指针（乐观锁版本）：迁移条件更新 WHERE current_seq=期望版本，
-- 两个操作者并发提交时仅一方 affected=1。
CREATE TABLE IF NOT EXISTS t_cage_migration_chain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_no VARCHAR(40) NOT NULL,
    batch_id BIGINT NOT NULL,
    origin_cage_no VARCHAR(32) NOT NULL,
    current_cage_no VARCHAR(32) NOT NULL,
    current_seq INT NOT NULL DEFAULT 0,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_migration_chain_no UNIQUE (chain_no),
    CONSTRAINT uk_migration_chain_batch UNIQUE (batch_id)
);

-- 迁移事件（历史台账）：只增不改不删（insert-only），任何迁移完成后快照不可被回写。
-- 固化原对象结束值与新对象起始值：鱼群估算量、累计投饵量（已落账口径）、最新存活率、
-- 传感器最新读数，以及迁移时刻各对象版本号，供前后对象逐项勾稽核对。
CREATE TABLE IF NOT EXISTS t_cage_migration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_no VARCHAR(40) NOT NULL,
    chain_id BIGINT NOT NULL,
    batch_id BIGINT NOT NULL,
    seq_no INT NOT NULL,
    transfer_type VARCHAR(16) NOT NULL,
    source_cage_no VARCHAR(32) NOT NULL,
    target_cage_no VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    operator_id BIGINT NOT NULL,
    operator_name VARCHAR(64) NOT NULL,
    -- 交接计量（新对象起始值必须等于原对象结束值）
    fish_estimate_count INTEGER NOT NULL,
    cumulative_feed_kg DECIMAL(18,2) NOT NULL,
    latest_survival_rate DECIMAL(7,4),
    feeding_plan_count INTEGER NOT NULL DEFAULT 0,
    feeding_record_count INTEGER NOT NULL DEFAULT 0,
    sensor_count INTEGER NOT NULL DEFAULT 0,
    -- 迁移时刻各对象版本：条件更新（CAS）凭证，并发提交只有一方版本匹配
    batch_version INT NOT NULL,
    plan_versions VARCHAR(2000),
    sensor_versions VARCHAR(4000),
    snapshot_json CLOB NOT NULL,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_migration_no UNIQUE (migration_no),
    CONSTRAINT uk_migration_chain_seq UNIQUE (chain_id, seq_no)
);
CREATE INDEX IF NOT EXISTS idx_migration_batch ON t_cage_migration (batch_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_migration_source ON t_cage_migration (source_cage_no, occurred_at);
CREATE INDEX IF NOT EXISTS idx_migration_target ON t_cage_migration (target_cage_no, occurred_at);

-- 被迁移对象的乐观锁版本列与迁移溯源列（H2 ALTER TABLE ADD ... 以“列不存在”为前提，
-- 全新库由本脚本创建；既有文件库重复执行时 IF NOT EXISTS 跳过）。
-- version：每次迁移/状态改写 +1，迁移 WHERE 旧版本条件更新，并发双方仅一方成功；
-- migrated_at：最后一次迁移发生时间（迁移时间点后该网箱的新数据才属于当前鱼群）；
-- migration_id：把对象当前状态锚定到使其落位的迁移事件。
ALTER TABLE t_fish_batch ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 0;
ALTER TABLE t_fish_batch ADD COLUMN IF NOT EXISTS migrated_at TIMESTAMP;
ALTER TABLE t_fish_batch ADD COLUMN IF NOT EXISTS migration_id BIGINT;

ALTER TABLE t_feeding_plan ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 0;
ALTER TABLE t_feeding_plan ADD COLUMN IF NOT EXISTS migrated_at TIMESTAMP;
ALTER TABLE t_feeding_plan ADD COLUMN IF NOT EXISTS migration_id BIGINT;

ALTER TABLE t_underwater_sensor ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 0;
ALTER TABLE t_underwater_sensor ADD COLUMN IF NOT EXISTS migrated_at TIMESTAMP;
ALTER TABLE t_underwater_sensor ADD COLUMN IF NOT EXISTS migration_id BIGINT;

-- 投饵记录与传感器读数为追加型流水：迁移后新发生的读数/投饵直接落在新网箱，
-- 历史读数保留原网箱编号不动，以 reading_time/feeding_time 与迁移时刻切分时间轴，
-- 并以迁移事件锚定其归属变化。
ALTER TABLE t_feeding_record ADD COLUMN IF NOT EXISTS migration_id BIGINT;
ALTER TABLE t_sensor_reading ADD COLUMN IF NOT EXISTS migration_id BIGINT;

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('cage-migration-5', '网箱替换/转移：不可断裂时间链、交接快照、乐观锁并发单版本、同事务迁移与投饵计划互斥');

-- 历史快照防回写（数据库层兜底）：迁移事件只增不改不删。
-- 应用层没有任何 update/delete 路径；触发器再拦截绕过应用的手工 SQL/其他连接。
-- H2 嵌入式按类名从应用 classpath 加载；BEFORE 触发器抛异常即回滚该语句。
CREATE TRIGGER IF NOT EXISTS trg_migration_no_update
BEFORE UPDATE ON t_cage_migration
FOR EACH ROW CALL "com.evops.aquaculture.trigger.MigrationImmutableTrigger";
CREATE TRIGGER IF NOT EXISTS trg_migration_no_delete
BEFORE DELETE ON t_cage_migration
FOR EACH ROW CALL "com.evops.aquaculture.trigger.MigrationImmutableTrigger";
