-- H2 本地文件数据库初始化脚本。
-- 深海网箱养殖：鱼苗批次、投饵计划、水下传感器、传感器读数、投饵记录、存活率报告、出网批次。

CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

-- 鱼苗批次（投放入网箱的一批鱼苗）
CREATE TABLE IF NOT EXISTS t_fish_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no VARCHAR(32) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    species VARCHAR(64) NOT NULL,
    fingerling_count INTEGER NOT NULL,
    average_weight_g DECIMAL(10,2),
    status VARCHAR(16) NOT NULL DEFAULT 'BREEDING',
    stocking_time TIMESTAMP NOT NULL,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_fish_batch_no UNIQUE (batch_no)
);
CREATE INDEX IF NOT EXISTS idx_fish_batch_cage ON t_fish_batch (cage_no);
CREATE INDEX IF NOT EXISTS idx_fish_batch_status ON t_fish_batch (status);

-- 投饵计划
CREATE TABLE IF NOT EXISTS t_feeding_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    feed_type VARCHAR(64) NOT NULL,
    daily_amount_kg DECIMAL(10,2) NOT NULL,
    feed_frequency INTEGER NOT NULL DEFAULT 1,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_feeding_plan_no UNIQUE (plan_no)
);
CREATE INDEX IF NOT EXISTS idx_feeding_plan_batch ON t_feeding_plan (batch_id);

-- 水下传感器
CREATE TABLE IF NOT EXISTS t_underwater_sensor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_no VARCHAR(32) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    sensor_type VARCHAR(32) NOT NULL,
    metric_unit VARCHAR(16) NOT NULL,
    depth_m DECIMAL(6,2),
    install_time TIMESTAMP NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ONLINE',
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sensor_no UNIQUE (sensor_no)
);
CREATE INDEX IF NOT EXISTS idx_sensor_cage ON t_underwater_sensor (cage_no);

-- 水下传感器读数
CREATE TABLE IF NOT EXISTS t_sensor_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_no VARCHAR(32) NOT NULL,
    sensor_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    metric_value DECIMAL(12,4) NOT NULL,
    reading_time TIMESTAMP NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sensor_reading_no UNIQUE (reading_no)
);
CREATE INDEX IF NOT EXISTS idx_reading_sensor_time ON t_sensor_reading (sensor_id, reading_time);
CREATE INDEX IF NOT EXISTS idx_reading_cage_time ON t_sensor_reading (cage_no, reading_time);

-- 投饵记录（实际投饵量；posted 表示已落账，落账后不可删除/不可改金额）
CREATE TABLE IF NOT EXISTS t_feeding_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    plan_id BIGINT,
    cage_no VARCHAR(32) NOT NULL,
    feed_type VARCHAR(64) NOT NULL,
    amount_kg DECIMAL(10,2) NOT NULL,
    feeding_time TIMESTAMP NOT NULL,
    posted SMALLINT NOT NULL DEFAULT 0,
    posted_time TIMESTAMP,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_feeding_record_no UNIQUE (record_no)
);
CREATE INDEX IF NOT EXISTS idx_feeding_record_batch ON t_feeding_record (batch_id);

-- 存活率报告
CREATE TABLE IF NOT EXISTS t_survival_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    alive_count INTEGER NOT NULL,
    survival_rate DECIMAL(7,4) NOT NULL,
    report_time TIMESTAMP NOT NULL,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_survival_report_no UNIQUE (report_no)
);
CREATE INDEX IF NOT EXISTS idx_survival_report_batch ON t_survival_report (batch_id);

-- 出网批次（accepted 表示已验收，验收后不可删除）
CREATE TABLE IF NOT EXISTS t_harvest_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_no VARCHAR(32) NOT NULL,
    fish_batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    harvest_count INTEGER NOT NULL,
    total_weight_kg DECIMAL(12,2) NOT NULL,
    harvest_time TIMESTAMP NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    accepted_time TIMESTAMP,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_harvest_no UNIQUE (harvest_no)
);
CREATE INDEX IF NOT EXISTS idx_harvest_fish_batch ON t_harvest_batch (fish_batch_id);

-- 定时/手工批量任务互斥锁：同一任务全局一行；owner_token 标识持锁执行方，
-- lease_expire_time 为租约到期时间：执行方异常退出（JVM 崩溃/kill -9）后租约到期，
-- 下一次触发可接管，不会永久阻塞。
CREATE TABLE IF NOT EXISTS t_task_lock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lock_name VARCHAR(64) NOT NULL,
    owner_token VARCHAR(64) NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    lease_expire_time TIMESTAMP NOT NULL,
    CONSTRAINT uk_task_lock_name UNIQUE (lock_name)
);

-- 任务执行台账：同一任务同一业务周期唯一一行。
-- RUNNING 执行中 / SUCCESS 成功（终态，重复触发短路）/ FAILED 失败（可重试）。
-- 成功终态 + (task_name, period) 唯一约束保证一个业务周期最多处理一次。
CREATE TABLE IF NOT EXISTS t_task_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name VARCHAR(64) NOT NULL,
    period VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    trigger_source VARCHAR(16),
    attempts INTEGER NOT NULL DEFAULT 1,
    posted_count INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(500),
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_task_run_period UNIQUE (task_name, period)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('aquaculture-2', '投饵监测批量落账定时任务：租约任务锁与业务周期幂等台账');

-- 网箱观测数据（CSV 批量导入落地区）。
-- 幂等业务键 = 航次号 + 网箱号 + 采样时刻（航次断网重复上传同一文件时，行级 upsert 保证不重复入账）。
-- 联动生成的投饵记录/存活率报告/传感器读数主键回写在本行上，用于“已落账/已验收不得覆盖”判定。
CREATE TABLE IF NOT EXISTS t_cage_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_no VARCHAR(32) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    observed_at TIMESTAMP NOT NULL,
    feed_amount_kg DECIMAL(10,2),
    survival_rate DECIMAL(7,4),
    sensor_value DECIMAL(12,4),
    sensor_unit VARCHAR(16),
    source_device VARCHAR(32),
    feeding_record_id BIGINT,
    survival_report_id BIGINT,
    sensor_reading_id BIGINT,
    import_id BIGINT NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cage_obs_key UNIQUE (voyage_no, cage_no, observed_at)
);
CREATE INDEX IF NOT EXISTS idx_cage_obs_cage ON t_cage_observation (cage_no, observed_at);
CREATE INDEX IF NOT EXISTS idx_cage_obs_voyage ON t_cage_observation (voyage_no);

-- 观测数据 CSV 导入批次台账：file_checksum（SHA-256）唯一。
-- 航次断网恢复后重复上传同一文件 → 校验和命中 → 直接返回首次处理结果（文件级幂等）；
-- 存在失败/未完成分片时续传这些分片（分片级重试）。
CREATE TABLE IF NOT EXISTS t_obs_import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_no VARCHAR(40) NOT NULL,
    file_name VARCHAR(255),
    file_checksum VARCHAR(64) NOT NULL,
    file_path VARCHAR(512),
    total_rows INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL,
    error_message VARCHAR(500),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_obs_import_no UNIQUE (import_no),
    CONSTRAINT uk_obs_import_checksum UNIQUE (file_checksum)
);

-- 导入分片台账：大文件按 shard-size 切分，逐片独立处理。
-- PENDING 待处理 / RUNNING 处理中（僵死可接管）/ SUCCESS 全部成功 / PARTIAL 完成但有失败行 / FAILED 分片级异常（可重试）。
CREATE TABLE IF NOT EXISTS t_obs_import_shard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL,
    shard_index INTEGER NOT NULL,
    start_idx INTEGER NOT NULL,
    end_idx INTEGER NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    row_count INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(500),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_obs_import_shard UNIQUE (import_id, shard_index)
);
CREATE INDEX IF NOT EXISTS idx_obs_shard_import ON t_obs_import_shard (import_id);

-- 逐行处理明细：每行一条（SUCCESS/UPDATED/SKIPPED/FAILED）。
-- 失败行保留原始行号、字段名、原始值与失败原因，供定位修复后重新上传。
CREATE TABLE IF NOT EXISTS t_obs_import_row (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL,
    shard_id BIGINT,
    line_no INTEGER NOT NULL,
    business_key VARCHAR(128),
    outcome VARCHAR(16) NOT NULL,
    field_name VARCHAR(32),
    raw_value VARCHAR(255),
    raw_line VARCHAR(1000),
    error_reason VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_obs_row_import ON t_obs_import_row (import_id, outcome);
CREATE INDEX IF NOT EXISTS idx_obs_row_shard ON t_obs_import_row (shard_id);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('obs-import-3', '观测数据CSV批量导入：校验和+业务键两级幂等、分片可重试、逐行隔离明细');
