-- H2 本地文件数据库初始化脚本。
-- 深海网箱养殖：鱼苗批次、投饵计划、水下传感器、传感器读数、投饵记录、存活率报告、出网批次。

CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

-- 鱼苗批次（投放入网箱的一批鱼苗）
CREATE TABLE IF NOT EXISTS t_fish_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no VARCHAR(32) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    species VARCHAR(64) NOT NULL,
    fingerling_count INTEGER NOT NULL,
    average_weight_g DECIMAL(10,2),
    status VARCHAR(16) NOT NULL DEFAULT 'BREEDING',
    stocking_time TIMESTAMP NOT NULL,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_fish_batch_no UNIQUE (batch_no)
);
CREATE INDEX IF NOT EXISTS idx_fish_batch_cage ON t_fish_batch (cage_no);
CREATE INDEX IF NOT EXISTS idx_fish_batch_status ON t_fish_batch (status);

-- 投饵计划
CREATE TABLE IF NOT EXISTS t_feeding_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    feed_type VARCHAR(64) NOT NULL,
    daily_amount_kg DECIMAL(10,2) NOT NULL,
    feed_frequency INTEGER NOT NULL DEFAULT 1,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_feeding_plan_no UNIQUE (plan_no)
);
CREATE INDEX IF NOT EXISTS idx_feeding_plan_batch ON t_feeding_plan (batch_id);

-- 水下传感器
CREATE TABLE IF NOT EXISTS t_underwater_sensor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_no VARCHAR(32) NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    sensor_type VARCHAR(32) NOT NULL,
    metric_unit VARCHAR(16) NOT NULL,
    depth_m DECIMAL(6,2),
    install_time TIMESTAMP NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ONLINE',
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sensor_no UNIQUE (sensor_no)
);
CREATE INDEX IF NOT EXISTS idx_sensor_cage ON t_underwater_sensor (cage_no);

-- 水下传感器读数
CREATE TABLE IF NOT EXISTS t_sensor_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_no VARCHAR(32) NOT NULL,
    sensor_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    metric_value DECIMAL(12,4) NOT NULL,
    reading_time TIMESTAMP NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sensor_reading_no UNIQUE (reading_no)
);
CREATE INDEX IF NOT EXISTS idx_reading_sensor_time ON t_sensor_reading (sensor_id, reading_time);
CREATE INDEX IF NOT EXISTS idx_reading_cage_time ON t_sensor_reading (cage_no, reading_time);

-- 投饵记录（实际投饵量；posted 表示已落账，落账后不可删除/不可改金额）
CREATE TABLE IF NOT EXISTS t_feeding_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    plan_id BIGINT,
    cage_no VARCHAR(32) NOT NULL,
    feed_type VARCHAR(64) NOT NULL,
    amount_kg DECIMAL(10,2) NOT NULL,
    feeding_time TIMESTAMP NOT NULL,
    posted SMALLINT NOT NULL DEFAULT 0,
    posted_time TIMESTAMP,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_feeding_record_no UNIQUE (record_no)
);
CREATE INDEX IF NOT EXISTS idx_feeding_record_batch ON t_feeding_record (batch_id);

-- 存活率报告
CREATE TABLE IF NOT EXISTS t_survival_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    alive_count INTEGER NOT NULL,
    survival_rate DECIMAL(7,4) NOT NULL,
    report_time TIMESTAMP NOT NULL,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_survival_report_no UNIQUE (report_no)
);
CREATE INDEX IF NOT EXISTS idx_survival_report_batch ON t_survival_report (batch_id);

-- 出网批次（accepted 表示已验收，验收后不可删除）
CREATE TABLE IF NOT EXISTS t_harvest_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_no VARCHAR(32) NOT NULL,
    fish_batch_id BIGINT NOT NULL,
    cage_no VARCHAR(32) NOT NULL,
    harvest_count INTEGER NOT NULL,
    total_weight_kg DECIMAL(12,2) NOT NULL,
    harvest_time TIMESTAMP NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    accepted_time TIMESTAMP,
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_harvest_no UNIQUE (harvest_no)
);
CREATE INDEX IF NOT EXISTS idx_harvest_fish_batch ON t_harvest_batch (fish_batch_id);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('aquaculture-1', '深海网箱养殖批次与投饵监测闭环');
